<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Taylor Okonek" />

<meta name="date" content="2022-06-08" />

<title>Descriptive statistics in rigr</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>
<script>// Hide empty <a> tag within highlighted CodeBlock for screen reader accessibility (see https://github.com/jgm/pandoc/issues/6352#issuecomment-626106786) -->
// v0.0.1
// Written by JooYoung Seo (jooyoung@psu.edu) and Atsushi Yasumoto on June 1st, 2020.

document.addEventListener('DOMContentLoaded', function() {
  const codeList = document.getElementsByClassName("sourceCode");
  for (var i = 0; i < codeList.length; i++) {
    var linkList = codeList[i].getElementsByTagName('a');
    for (var j = 0; j < linkList.length; j++) {
      if (linkList[j].innerHTML === "") {
        linkList[j].setAttribute('aria-hidden', 'true');
      }
    }
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Descriptive statistics in rigr</h1>
<h4 class="author">Taylor Okonek</h4>
<h4 class="date">2022-06-08</h4>



<p>A key feature of many exploratory analyses is obtaining descriptive statistics for multiple variables. In the <code>rigr</code> package, we provide a function <code>descrip()</code> with improved output for descriptive statistics for an arbitrary number of variables. Key features include the ability to easily compute summary measures on strata or subsets of the variables specified. We go through examples making use of these key features below.</p>
<div id="descriptive-statistics-with-descrip" class="section level1">
<h1>Descriptive statistics with <code>descrip</code></h1>
<p>Throughout our examples, we’ll use the <code>fev</code> dataset. This dataset is included in the <code>rigr</code> package; see its documentation by running <code>?fev</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co">## Preparing our R session</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">library</span>(rigr)</span></code></pre></div>
<pre><code>## rigr version 1.0.3: Regression, Inference, and General Data Analysis Tools in R</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="kw">data</span>(fev)</span></code></pre></div>
<p>First, we can obtain default descriptive statistics for the dataset simply by running <code>descrip()</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="kw">descrip</span>(fev)</span></code></pre></div>
<pre><code>##           N     Msng  Mean      Std Dev    Min       25%       Mdn     
## seqnbr:     654     0   327.5     188.9     1.000     164.2     327.5  
## subjid:     654     0   37170     23691     201.0     15811     36071  
##    age:     654     0   9.931     2.954     3.000     8.000     10.00  
##    fev:     654     0   2.637     0.8671    0.7910    1.981     2.547  
## height:     654     0   61.14     5.704     46.00     57.00     61.50  
##    sex:     654     0   1.514     0.5002    1.000     1.000     2.000  
##  smoke:     654     0   1.099     0.2994    1.000     1.000     1.000  
##            75%       Max     
## seqnbr:     490.8     654.0  
## subjid:     53638     90001  
##    age:     12.00     19.00  
##    fev:     3.118     5.793  
## height:     65.50     74.00  
##    sex:     2.000     2.000  
##  smoke:     1.000     2.000</code></pre>
<p>Since we input a dataframe, we can see that all variables have the same number of elements given in the <code>N</code> column. None of our variables have any missing values, as seen in the <code>Msng</code> column.</p>
<p>Rather than specifying the whole dataframe, if we are interested in only the variables <code>fev</code> and <code>height</code>, we can input only those two vectors into the <code>descrip()</code> function, as below.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="kw">descrip</span>(fev<span class="op">$</span>fev, fev<span class="op">$</span>height)</span></code></pre></div>
<pre><code>##               N     Msng  Mean      Std Dev    Min       25%       Mdn     
##    fev$fev:     654     0   2.637     0.8671    0.7910    1.981     2.547  
## fev$height:     654     0   61.14     5.704     46.00     57.00     61.50  
##                75%       Max     
##    fev$fev:     3.118     5.793  
## fev$height:     65.50     74.00</code></pre>
</div>
<div id="descriptive-statistics-for-strata" class="section level1">
<h1>Descriptive statistics for strata</h1>
<p>Suppose we wish to obtain descriptive statistics of the <code>fev</code> and <code>height</code> variables, stratified by smoking status. To do this, we can use the <code>strata</code> parameter in <code>descrip</code>:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="kw">descrip</span>(fev<span class="op">$</span>fev, fev<span class="op">$</span>height, <span class="dt">strata =</span> fev<span class="op">$</span>smoke)</span></code></pre></div>
<pre><code>##                         N     Msng  Mean      Std Dev    Min       25%     
##    fev$fev:  All          654     0   2.637     0.8671    0.7910    1.981  
##    fev$fev:    Str  no    589     0   2.566     0.8505    0.7910    1.920  
##    fev$fev:    Str  yes    65     0   3.277     0.7500    1.694     2.795  
## fev$height:  All          654     0   61.14     5.704     46.00     57.00  
## fev$height:    Str  no    589     0   60.61     5.672     46.00     57.00  
## fev$height:    Str  yes    65     0   65.95     3.193     58.00     63.50  
##                          Mdn       75%       Max     
##    fev$fev:  All          2.547     3.118     5.793  
##    fev$fev:    Str  no    2.465     3.048     5.793  
##    fev$fev:    Str  yes   3.169     3.751     4.872  
## fev$height:  All          61.50     65.50     74.00  
## fev$height:    Str  no    61.00     64.50     74.00  
## fev$height:    Str  yes   66.00     68.00     72.00</code></pre>
<p>In the output, we can see that overall descriptive statistics, as well as descriptive statistics for each stratum (smoke = 1, smoke = 2) are returned in the table.</p>
</div>
<div id="descriptive-statistics-for-subsets" class="section level1">
<h1>Descriptive statistics for subsets</h1>
<p>Now suppose we only want descriptive statistics for height and FEV for individuals over the age of 10. We first create an indicator variable for <code>age &gt; 10</code> <em>outside</em> of the <code>descrip()</code> function, and then give this variable to the <code>subset</code> parameter.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>greater_<span class="dv">10</span> &lt;-<span class="st"> </span><span class="kw">ifelse</span>(fev<span class="op">$</span>age <span class="op">&gt;</span><span class="st"> </span><span class="dv">10</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="kw">descrip</span>(fev<span class="op">$</span>fev, fev<span class="op">$</span>height, <span class="dt">subset =</span> greater_<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##               N     Msng  Mean      Std Dev    Min       25%       Mdn     
##    fev$fev:     264     0   1.708     0.0000    1.708     1.708     1.708  
## fev$height:     264     0   57.00     0.0000    57.00     57.00     57.00  
##                75%       Max     
##    fev$fev:     1.708     1.708  
## fev$height:     57.00     57.00</code></pre>
</div>
<div id="abovebelow" class="section level1">
<h1>Above/Below</h1>
<p>Suppose we want to know the proportion of individuals with FEV greater than 2, stratified by smoking status. We can use the <code>strata</code> argument as before, in addition to the <code>above</code> parameter to obtain this set of descriptive statistics:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="kw">descrip</span>(fev<span class="op">$</span>fev, <span class="dt">strata =</span> fev<span class="op">$</span>smoke, <span class="dt">above =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                      N     Msng  Mean      Std Dev    Min       25%     
## fev$fev:  All          654     0   2.637     0.8671    0.7910    1.981  
## fev$fev:    Str  no    589     0   2.566     0.8505    0.7910    1.920  
## fev$fev:    Str  yes    65     0   3.277     0.7500    1.694     2.795  
##                       Mdn       75%       Max      Pr&gt;2     
## fev$fev:  All          2.547     3.118     5.793     0.7446 
## fev$fev:    Str  no    2.465     3.048     5.793     0.7199 
## fev$fev:    Str  yes   3.169     3.751     4.872     0.9692</code></pre>
<p>From the output, we can see that 96.92% of the individuals in this dataset who smoke (smoking status 1) had an FEV greater than 2 L/sec, and 71.99% of the individuals in this dataset who were nonsmokers had an FEV greater than 2 L/sec. </p>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
