<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Taylor Okonek, Brian D. Williamson and Amy D. Willis" />

<meta name="date" content="2021-09-14" />

<title>Regression in rigr</title>

<script src="data:application/javascript;base64,Ly8gUGFuZG9jIDIuOSBhZGRzIGF0dHJpYnV0ZXMgb24gYm90aCBoZWFkZXIgYW5kIGRpdi4gV2UgcmVtb3ZlIHRoZSBmb3JtZXIgKHRvCi8vIGJlIGNvbXBhdGlibGUgd2l0aCB0aGUgYmVoYXZpb3Igb2YgUGFuZG9jIDwgMi44KS4KZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsIGZ1bmN0aW9uKGUpIHsKICB2YXIgaHMgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCJkaXYuc2VjdGlvbltjbGFzcyo9J2xldmVsJ10gPiA6Zmlyc3QtY2hpbGQiKTsKICB2YXIgaSwgaCwgYTsKICBmb3IgKGkgPSAwOyBpIDwgaHMubGVuZ3RoOyBpKyspIHsKICAgIGggPSBoc1tpXTsKICAgIGlmICghL15oWzEtNl0kL2kudGVzdChoLnRhZ05hbWUpKSBjb250aW51ZTsgIC8vIGl0IHNob3VsZCBiZSBhIGhlYWRlciBoMS1oNgogICAgYSA9IGguYXR0cmlidXRlczsKICAgIHdoaWxlIChhLmxlbmd0aCA+IDApIGgucmVtb3ZlQXR0cmlidXRlKGFbMF0ubmFtZSk7CiAgfQp9KTsK"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="data:text/css,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" type="text/css" />




</head>

<body>




<h1 class="title toc-ignore">Regression in rigr</h1>
<h4 class="author">Taylor Okonek, Brian D. Williamson and Amy D. Willis</h4>
<h4 class="date">2021-09-14</h4>



<p>In the <code>rigr</code> package, we have set out to make regression and analysis easier by</p>
<ol style="list-style-type: decimal">
<li>allowing you to specify different types of regression from one function;</li>
<li>automatically computing confidence intervals and p-values using robust standard errors;</li>
<li>displaying output in a more intuitive fashion than base R; and</li>
<li>allowing you to specify multiple-partial F-tests.</li>
</ol>
<p>This capability is implemented in the function <code>regress()</code>. The basic arguments to this function are</p>
<ul>
<li><code>fnctl</code>: the functional</li>
<li><code>formula</code>: the formula for the linear model</li>
<li><code>data</code>: the data to use for the model</li>
</ul>
<div id="fnctl-the-functional" class="section level2">
<h2><code>fnctl</code>: the functional</h2>
<p>We use the concept of a <em>functional</em> to handle our first goal: allowing you to specify different types of regression models using a single function. A functional takes a <em>function</em> as its argument and returns a number. The most common example of a functional in regression is the <em>mean</em>. The allowed functionals to <code>regress()</code> are</p>
<table>
<colgroup>
<col width="27%" />
<col width="36%" />
<col width="36%" />
</colgroup>
<thead>
<tr class="header">
<th>Functional</th>
<th align="left">Type of Regression</th>
<th align="left">base R command</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>&quot;mean&quot;</code></td>
<td align="left">Linear Regression</td>
<td align="left"><code>lm()</code></td>
</tr>
<tr class="even">
<td><code>&quot;geometric mean&quot;</code></td>
<td align="left">Linear Regression on logarithmically transformed Y</td>
<td align="left"><code>lm()</code>, with Y log-transformed</td>
</tr>
<tr class="odd">
<td><code>&quot;odds&quot;</code></td>
<td align="left">Logistic Regression</td>
<td align="left"><code>glm(family = binomial)</code></td>
</tr>
<tr class="even">
<td><code>&quot;rate&quot;</code></td>
<td align="left">Poisson Regression</td>
<td align="left"><code>glm(family = poisson)</code></td>
</tr>
</tbody>
</table>
</div>
<div id="formula-and-data" class="section level2">
<h2><code>formula</code> and <code>data</code></h2>
<p>The <em>formula</em> to <code>regress()</code> is the same as a formula given to <code>lm()</code> or <code>glm()</code>, but with additional optional functionality to enable sophisticated analyses (multiple partial F-tests) with fewer headaches.</p>
<!-- To allow users to specify multiple partial F-tests, we have added a special function - `U()` - which can be added to the formula. `regress()` will compute an F statistic for all variables included inside the `U()` specification. -->
<p>The <em>data</em> argument is exactly the same as that in <code>lm()</code> or any of the other regression commands.</p>
</div>
<div id="linear-regression" class="section level1">
<h1>Linear Regression</h1>
<p>As a first example, we run a linear regression of atrophy (a measure of global brain activity) on age, sex and race, from the <code>mri</code> data. This dataset is included in the <code>rigr</code> package; see its documentation by running <code>?mri</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Preparing our R session</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rigr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mri)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;mean&quot;</span>, atrophy <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> race, <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ age + sex + race, 
##     data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -34.120  -8.331  -0.434   7.325  53.915 
## 
## Coefficients:
##                                                          Estimate  Naive SE 
## [1] Intercept                                             -17.60     6.341  
## [2] age                                                    0.6866   0.08134 
## [3] sexMale                                                5.988     0.8867 
##     race                                                                    
## [4]    Black                                              -2.375     2.109  
## [5]    Subject did not identify White, Black or Asian     -3.078     3.885  
## [6]    White                                              -0.2664    1.822  
##                                                          Robust SE    95%L     
## [1] Intercept                                              6.893       -31.14  
## [2] age                                                   0.08836       0.5132 
## [3] sexMale                                                0.8895       4.242  
##     race                                                                       
## [4]    Black                                               2.049       -6.397  
## [5]    Subject did not identify White, Black or Asian      4.157       -11.24  
## [6]    White                                               1.780       -3.761  
##                                                          95%H         F stat   
## [1] Intercept                                             -4.072           6.52
## [2] age                                                    0.8601         60.38
## [3] sexMale                                                7.734          45.32
##     race                                                                   1.14
## [4]    Black                                               1.647           1.34
## [5]    Subject did not identify White, Black or Asian      5.082           0.55
## [6]    White                                               3.228           0.02
##                                                          df Pr(&gt;F)   
## [1] Intercept                                            1    0.0109 
## [2] age                                                  1  &lt; 0.00005
## [3] sexMale                                              1  &lt; 0.00005
##     race                                                 3    0.3315 
## [4]    Black                                             1    0.2467 
## [5]    Subject did not identify White, Black or Asian    1    0.4592 
## [6]    White                                             1    0.8810 
## 
## Residual standard error: 12 on 729 degrees of freedom
## Multiple R-squared:  0.1439, Adjusted R-squared:  0.138 
## F-statistic: 21.32 on 5 and 729 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Notice that by default robust standard error estimates are returned in addition to the naive estimates. The robust estimates are also used to perform inference. Thus, the confidence intervals, statistics, and p-values use these estimates of the standard error.</p>
<p>F-statistics are also displayed by default, including the multiple partial F-tests for the levels of a multi-level category (such as <code>race</code>) as well as the overall F-test for the variable.</p>
</div>
<div id="generalized-linear-regression" class="section level1">
<h1>Generalized Linear Regression</h1>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<p>We can also run generalized linear regression using <code>regress()</code>. For example, to model the odds of having diabetes for males compared to females, we could run a logistic regression as follows:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;odds&quot;</span>, diabetes <span class="sc">~</span> sex, <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;odds&quot;, formula = diabetes ~ sex, data = mri)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.5593  -0.5593  -0.3823  -0.3823   2.3034  
## 
## Coefficients:
## 
## Raw Model:
##                  Estimate  Naive SE  Robust SE       F stat    df Pr(&gt;F)   
## [1] Intercept     -2.580     0.2034    0.2037           160.39 1  &lt; 0.00005
## [2] sexMale        0.8037    0.2519    0.2522            10.15 1    0.0015 
## 
## Transformed Model:
##                  e(Est)    e(95%L)   e(95%H)         F stat    df Pr(&gt;F)   
## [1] Intercept     0.07580   0.05082    0.1131           160.39 1  &lt; 0.00005
## [2] sexMale        2.234     1.361     3.665             10.15 1    0.0015 
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 501.59  on 734  degrees of freedom
## Residual deviance: 490.82  on 733  degrees of freedom
## AIC: 494.82
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>In all of the generalized linear regression output we see two tables. The <code>Raw Model</code> table displays estimated coefficients (and their standard errors) on the log-odds scale. The <code>Transformed Model</code> table exponentiates the estimated coefficients and their confidence intervals so that the estimated parameters can be interpreted on the odds scale.</p>
<p>Note that the only possible link function in <code>regress</code> with <code>fnctl = odds&quot;</code> is the logit link. Similarly, the only possible link function in <code>regress</code> with <code>fnctl = &quot;rate&quot;</code> is the log link.</p>
</div>
<div id="poisson-regression" class="section level2">
<h2>Poisson Regression</h2>
<p>The final functional that <code>regress</code> supports is <code>&quot;rate&quot;</code>, for use in Poisson regression. To regress <code>yrsquit</code> on <code>age</code>, we would run:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;rate&quot;</span>, yrsquit <span class="sc">~</span> age, <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;rate&quot;, formula = yrsquit ~ age, data = mri)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -5.385  -4.365  -4.186   2.395   9.920  
## 
## Coefficients:
## 
## Raw Model:
##                  Estimate  Naive SE   Robust SE        F stat    df Pr(&gt;F)   
## [1] Intercept      1.011     0.1571     0.7239              1.95 1    0.1629 
## [2] age           0.01680   2.087e-03  9.688e-03            3.01 1    0.0834 
## 
## Transformed Model:
##                  e(Est)    e(95%L)   e(95%H)         F stat    df Pr(&gt;F)   
## [1] Intercept      2.749     0.6637    11.39              1.95 1    0.1629 
## [2] age            1.017     0.9978    1.036              3.01 1    0.0834 
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 14574  on 734  degrees of freedom
## Residual deviance: 14511  on 733  degrees of freedom
## AIC: 16008
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Note that again we have two tables of output, denoted by <code>Raw Model</code> and <code>Transformed Model</code>, with <code>Transformed Model</code> displaying exponentiated estimated coefficients.</p>
</div>
</div>
<div id="regression-on-the-geometric-mean" class="section level1">
<h1>Regression on the Geometric Mean</h1>
<p>Most often in linear regression we are interested in modeling the mean of the response variable. However, we are sometimes interested in modeling the mean of the log-transformed response variable, which allows us to make statements about the geometric mean of the response. In <code>regress()</code>, we can use the <code>&quot;geometric mean&quot;</code> functional to fit this model. Regression on the geometric mean of the <code>packyrs</code> variable in the <code>mri</code> dataset can be performed as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;geometric mean&quot;</span>, packyrs <span class="sc">~</span> age, <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## ( 1  cases deleted due to missing values)
## 
## 
## Call:
## regress(fnctl = &quot;geometric mean&quot;, formula = packyrs ~ age, data = mri)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -4.136 -3.417  1.283  2.970  5.219 
## 
## Coefficients:
## 
## Raw Model:
##                  Estimate  Naive SE  Robust SE       F stat    df Pr(&gt;F)   
## [1] Intercept      6.410     1.586     1.537             17.39 1  &lt; 0.00005
## [2] age          -0.07986   0.02121   0.02050            15.17 1     1e-04 
## 
## Transformed Model:
##                  e(Est)    e(95%L)   e(95%H)         F stat    df Pr(&gt;F)   
## [1] Intercept      608.1     29.74     12431             17.39 1  &lt; 0.00005
## [2] age            0.9232    0.8868    0.9612            15.17 1     1e-04 
## 
## Residual standard error: 3.13 on 732 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.01899,    Adjusted R-squared:  0.01765 
## F-statistic: 15.17 on 1 and 732 DF,  p-value: 0.0001074</code></pre>
<p>It should be noted that many of the <code>packyrs</code> observations are zero, but the geometric mean of data including an observation of zero is zero… regardless of how many non-zeros were also observed. Therefore, by default, zeroes in the outcome variable are replaced by a value equal to one-half the lowest nonzero value in the outcome variable. This is based on the idea that the lowest observed value could be a proxy for the lower limit of detection. If you wish to specify a different value with which to replace zeroes, you may do say using the <code>replaceZeroes</code> argument.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;geometric mean&quot;</span>, packyrs <span class="sc">~</span> age, <span class="at">data =</span> mri, <span class="at">replaceZeroes =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## ( 1  cases deleted due to missing values)
## 
## 
## Call:
## regress(fnctl = &quot;geometric mean&quot;, formula = packyrs ~ age, data = mri, 
##     replaceZeroes = 1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.6437 -1.7460  0.0625  1.7259  3.8246 
## 
## Coefficients:
## 
## Raw Model:
##                  Estimate  Naive SE  Robust SE       F stat    df Pr(&gt;F)   
## [1] Intercept      5.119     0.8887    0.8462            36.60 1  &lt; 0.00005
## [2] age          -0.04498   0.01189   0.01127            15.93 1     1e-04 
## 
## Transformed Model:
##                  e(Est)    e(95%L)   e(95%H)         F stat    df Pr(&gt;F)   
## [1] Intercept      167.2     31.76     880.7             36.60 1  &lt; 0.00005
## [2] age            0.9560    0.9351    0.9774            15.93 1     1e-04 
## 
## Residual standard error: 1.754 on 732 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.01919,    Adjusted R-squared:  0.01785 
## F-statistic: 15.93 on 1 and 732 DF,  p-value: 7.218e-05</code></pre>
<p>In the output from regress using the geometric mean functional, we see a table for the <code>Raw Model</code> and the <code>Transformed Model</code>. The <code>e(Est)</code>, <code>e(95%L)</code>, and <code>e(95%H)</code> columns in the <code>Transformed Model</code> table correspond to exponentiated values from the <code>Raw Model</code> - you’ll notice that <span class="math inline">\(e^{5.119} \approx 167.2.\)</span></p>
</div>
<div id="re-parameterizations-of-a-variable" class="section level1">
<h1>Re-parameterizations of a Variable</h1>
<p>There are two special functions in <code>rigr</code> which allow us to re-parameterize variables:</p>
<ul>
<li><code>dummy</code>: create dummy variables</li>
<li><code>polynomial</code>: create a polynomial</li>
</ul>
<p>Both of these functions may be used in a <code>regress()</code> call, and will additionally give a multiple partial F-test of the entire variable automatically.</p>
<div id="specifying-the-reference-group-with-dummy" class="section level2">
<h2>Specifying the reference group with <code>dummy</code></h2>
<p>The <code>dummy</code> function is useful for specifying the reference group that you wish to use with categorical variables. Below we show an example of using the reference group “Female” vs. the reference group “Male” in a regression on <code>sex</code>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;mean&quot;</span>, atrophy <span class="sc">~</span> <span class="fu">dummy</span>(sex, <span class="at">reference =</span> <span class="st">&quot;Male&quot;</span>), <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ dummy(sex, reference = &quot;Male&quot;), 
##     data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -29.087  -9.087  -0.905   8.095  49.095 
## 
## Coefficients:
##                                         Estimate  Naive SE  Robust SE   
## [1] Intercept                             39.09     0.6563    0.6733    
## [2]   dummy(sex, reference = &quot;Male&quot;)     -6.182     0.9263    0.9265    
##                                         95%L      95%H         F stat    df
## [1] Intercept                             37.77     40.41        3370.22 1 
## [2]   dummy(sex, reference = &quot;Male&quot;)     -8.001    -4.363          44.53 1 
##                                         Pr(&gt;F)   
## [1] Intercept                           &lt; 0.00005
## [2]   dummy(sex, reference = &quot;Male&quot;)    &lt; 0.00005
## 
##  Dummy terms calculated from sex, reference = Male 
## 
## Residual standard error: 12.56 on 733 degrees of freedom
## Multiple R-squared:  0.05729,    Adjusted R-squared:  0.05601 
## F-statistic: 44.53 on 1 and 733 DF,  p-value: 4.944e-11</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;mean&quot;</span>, atrophy <span class="sc">~</span> <span class="fu">dummy</span>(sex, <span class="at">reference =</span> <span class="st">&quot;Female&quot;</span>), <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ dummy(sex, reference = &quot;Female&quot;), 
##     data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -29.087  -9.087  -0.905   8.095  49.095 
## 
## Coefficients:
##                                           Estimate  Naive SE  Robust SE   
## [1] Intercept                               32.91     0.6536    0.6364    
## [2]   dummy(sex, reference = &quot;Female&quot;)      6.182     0.9263    0.9265    
##                                           95%L      95%H         F stat    df
## [1] Intercept                               31.66     34.15        2673.43 1 
## [2]   dummy(sex, reference = &quot;Female&quot;)      4.363     8.001          44.53 1 
##                                           Pr(&gt;F)   
## [1] Intercept                             &lt; 0.00005
## [2]   dummy(sex, reference = &quot;Female&quot;)    &lt; 0.00005
## 
##  Dummy terms calculated from sex, reference = Female 
## 
## Residual standard error: 12.56 on 733 degrees of freedom
## Multiple R-squared:  0.05729,    Adjusted R-squared:  0.05601 
## F-statistic: 44.53 on 1 and 733 DF,  p-value: 4.944e-11</code></pre>
<p>Notice that below the coefficients table in the output, the reference category is reported.</p>
</div>
<div id="polynomial-regression" class="section level2">
<h2>Polynomial regression</h2>
<p>You can fit higher-order polynomials using <code>polynomial</code>:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;mean&quot;</span>, atrophy <span class="sc">~</span> <span class="fu">polynomial</span>(age, <span class="at">degree =</span> <span class="dv">2</span>), <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ polynomial(age, degree = 2), 
##     data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.828  -9.063  -1.018   7.816  50.887 
## 
## Coefficients:
##                                    Estimate  Naive SE  Robust SE    95%L      
## [1] Intercept                        35.34     0.5598    0.5622        34.24  
##     polynomial(age, degree = 2)                                               
## [2]    age^1                         0.5869    0.1009   0.09808       0.3943  
## [3]    age^2                        0.02159   0.01099   0.01150     -9.897e-04
##                                    95%H         F stat    df Pr(&gt;F)   
## [1] Intercept                        36.45        3952.13 1  &lt; 0.00005
##     polynomial(age, degree = 2)                     32.91 2  &lt; 0.00005
## [2]    age^1                         0.7794         35.80 1  &lt; 0.00005
## [3]    age^2                        0.04417          3.52 1    0.0609 
## 
##  Polynomial terms calculated from age, centered at 74.566 
## 
## Residual standard error: 12.33 on 732 degrees of freedom
## Multiple R-squared:  0.09148,    Adjusted R-squared:  0.089 
## F-statistic: 32.91 on 2 and 732 DF,  p-value: 2.06e-14</code></pre>
<p>Note that all polynomials less than or equal to the degree specified are included in the model, and that the variables in the polynomial specification are mean-centered by default. You can change the centering using the <code>center</code> parameter in the polynomial function, an example of which is as follows.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;mean&quot;</span>, atrophy <span class="sc">~</span> <span class="fu">polynomial</span>(age, <span class="at">degree =</span> <span class="dv">2</span>, <span class="at">center =</span> <span class="dv">65</span>), <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ polynomial(age, degree = 2, 
##     center = 65), data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.828  -9.063  -1.018   7.816  50.887 
## 
## Coefficients:
##                                                 Estimate  Naive SE 
## [1] Intercept                                     31.70     1.528  
##     polynomial(age, degree = 2, center = 65)                       
## [2]    age^1                                      0.1738    0.2797 
## [3]    age^2                                     0.02159   0.01099 
##                                                 Robust SE    95%L      
## [1] Intercept                                     1.497         28.77  
##     polynomial(age, degree = 2, center = 65)                           
## [2]    age^1                                      0.2811      -0.3781  
## [3]    age^2                                     0.01150     -9.897e-04
##                                                 95%H         F stat    df
## [1] Intercept                                     34.64         448.45 1 
##     polynomial(age, degree = 2, center = 65)                     32.91 2 
## [2]    age^1                                      0.7257          0.38 1 
## [3]    age^2                                     0.04417          3.52 1 
##                                                 Pr(&gt;F)   
## [1] Intercept                                   &lt; 0.00005
##     polynomial(age, degree = 2, center = 65)    &lt; 0.00005
## [2]    age^1                                      0.5367 
## [3]    age^2                                      0.0609 
## 
##  Polynomial terms calculated from age, centered at 65 
## 
## Residual standard error: 12.33 on 732 degrees of freedom
## Multiple R-squared:  0.09148,    Adjusted R-squared:  0.089 
## F-statistic: 32.91 on 2 and 732 DF,  p-value: 2.06e-14</code></pre>
</div>
</div>
<div id="user-specified-multiple-partial-f-tests" class="section level1">
<h1>User-specified multiple partial F-tests</h1>
<p>You can also perform multiple partial F-tests using formulas and the <code>U</code> function. This is useful when want to test a subset of variables all at once in your regression. For example, to test whether both the variables <code>packyrs</code> and <code>yrsquit</code> are associated with <code>atrophy</code> in a model with age as a predictor, we can run</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regress</span>(<span class="st">&quot;mean&quot;</span>, atrophy <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> <span class="fu">U</span>(<span class="st">&quot;Smoking variables&quot;</span> <span class="ot">=</span> <span class="er">~</span>packyrs <span class="sc">+</span> yrsquit), <span class="at">data =</span> mri)</span></code></pre></div>
<pre><code>## ( 1  cases deleted due to missing values)
## 
## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ age + sex + U(`Smoking variables` = ~packyrs + 
##     yrsquit), data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.593  -8.613  -0.306   7.279  52.399 
## 
## Coefficients:
##                          Estimate   Naive SE  Robust SE    95%L      95%H     
## [1] Intercept              -18.82     6.167     6.690       -31.95    -5.683  
## [2] age                    0.6917    0.08212   0.08900       0.5170    0.8664 
## [3] sexMale                 5.628     0.9386    0.9596       3.744     7.512  
##     Smoking variables                                                         
## [4]   packyrs             9.782e-03  0.01684   0.01693     -0.02346   0.04302 
## [5]   yrsquit              0.02071   0.03282   0.03276     -0.04361   0.08503 
##                             F stat    df Pr(&gt;F)   
## [1] Intercept                    7.91 1    0.0050 
## [2] age                         60.40 1  &lt; 0.00005
## [3] sexMale                     34.39 1  &lt; 0.00005
##     Smoking variables            0.37 2    0.6905 
## [4]   packyrs                    0.33 1    0.5636 
## [5]   yrsquit                    0.40 1    0.5275 
## 
## Residual standard error: 11.99 on 729 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.1419, Adjusted R-squared:  0.1372 
## F-statistic: 26.44 on 4 and 729 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><code>&quot;Smoking variables&quot;</code> is what we name the group of variables <code>packyrs</code> and <code>yrsquit</code>. The overall F statistic and p-value associated with the inclusion of these two smoking variables variables in the model are 4.37 and 0.0130, respectively.</p>
</div>
<div id="testing-contrasts-hypotheses-about-linear-combinations-of-regression-coefficients" class="section level1">
<h1>Testing contrasts: hypotheses about linear combinations of regression coefficients</h1>
<p>You may be interested in testing a null hypothesis about a linear combination of coefficients in our regression model. For example, to investigate “Is the mean atrophy for a female subject equal to the mean atrophy for a male subject who is 10 years younger?”, our hypothesis test involves both the coefficients on age and sex. We can test this hypothesis using the <code>lincom</code> function. First, we need to fit a linear model of age and sex on atrophy:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mod_rigr <span class="ot">&lt;-</span> <span class="fu">regress</span>(<span class="st">&quot;mean&quot;</span>, atrophy <span class="sc">~</span> age <span class="sc">+</span> sex, <span class="at">data =</span> mri)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mod_rigr</span></code></pre></div>
<pre><code>## 
## Call:
## regress(fnctl = &quot;mean&quot;, formula = atrophy ~ age + sex, data = mri)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.765  -8.582  -0.356   7.344  52.100 
## 
## Coefficients:
##                  Estimate  Naive SE  Robust SE    95%L      95%H     
## [1] Intercept     -17.83     6.081     6.557       -30.70    -4.959  
## [2] age            0.6819   0.08129   0.08769       0.5097    0.8540 
## [3] sexMale        5.964     0.8857    0.8845       4.227     7.700  
##                     F stat    df Pr(&gt;F)   
## [1] Intercept            7.40 1    0.0067 
## [2] age                 60.47 1  &lt; 0.00005
## [3] sexMale             45.46 1  &lt; 0.00005
## 
## Residual standard error: 12 on 732 degrees of freedom
## Multiple R-squared:   0.14,  Adjusted R-squared:  0.1376 
## F-statistic: 52.18 on 2 and 732 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We then create a vector giving the linear combination of the coefficient that we hypothesized to be zero, and perform the test using <code>lincom</code>. The elements in <code>mod_combo</code> correspond to <code>Intercept</code>, <code>age</code>, and <code>sexMale</code>, because this was their order in the coefficient table shown above.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mod_combo <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">10</span>, <span class="dv">1</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lincom</span>(mod_rigr, mod_combo)</span></code></pre></div>
<pre><code>## 
## H0: -10*age+1*sexMale   =  
## Ha: -10*age+1*sexMale  !=  
##      Estimate Std. Err.   95%L   95%H      T Pr(T &gt; |t|)
## [1,]   -0.855     1.236 -3.282  1.571 -0.692       0.489</code></pre>
<p>Note that the standard errors returned by default are robust, as are the associated confidence intervals and p-values.</p>
<p>We could also test the null hypothesis that the mean difference in atrophy between these two groups (females, and males 10 years younger) is equal to -1 as follows:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lincom</span>(mod_rigr, mod_combo, <span class="at">null.hypoth =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## H0: -10*age+1*sexMale   =  
## Ha: -10*age+1*sexMale  !=  
##      Estimate Std. Err.   95%L   95%H     T Pr(T &gt; |t|)
## [1,]   -0.855     1.236 -3.282  1.571 0.117       0.907</code></pre>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
